// vue-v/src/pages/Auth/AuthLayout.vue
<template>
  <div
    class="min-h-screen flex items-center justify-center bg-linear-to-br from-blue-50 to-white px-4"
  >
    <div class="w-full max-w-md bg-white rounded-2xl shadow-lg p-8">
      <h2 class="text-2xl font-semibold text-center mb-6">{{ title }}</h2>
      <slot />
    </div>
  </div>
</template>

<script setup>
defineProps({ title: String })
</script>

// react-v/src/pages/AuthLayout.jsx
export default function AuthLayout({ title, children }) {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-linear-to-br from-blue-50 to-white px-4">
      <div className="w-full max-w-md bg-white rounded-2xl shadow-lg p-8">
        <h2 className="text-2xl font-semibold text-center mb-6 text-gray-800">
          {title}
        </h2>
        {children}
      </div>
    </div>
  );
}
